spring:
    datasource:
        url: jdbc:oracle:thin:@mcjang.iptime.org:1521:XE
#        url: jdbc:oracle:thin:@192.168.211.12:1521:XE
#        url: jdbc:oracle:thin:@localhost:1521:XE
#        driver-class-name: oracle.jdbc.driver.OracleDriver
        username: BTEAM
        password: bteam
#        username: COOKCCOOK
#        password: ck1234
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    servlet:
        multipart:
            # 업로드 파일의 최대 크기 설정 (100mb == 1024byte * 1024 *100)
            max-file-size: 104857600
            # 사용자 요청당 업로드할 수 있는 파일의 크기 설정 (10mb)
            max-request-size: 10485760
    security:
        oauth2:
          resourceserver:
              jwt:
                  issuer-uri: krait4g@gmail.com
                  secret-key: spring-security-secret-key-random-token-key
          client:
              registration:
                  google:
                      client-id: 977513587021-hjt1t5e9fie6dv93vsiogqrj1cqges27.apps.googleusercontent.com
                      client-secret: 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
                      scope:
                          - email
                          - profile
                          
#젠킨스용
#                  google:
#                      client-id: 359584162819-bra9rhhhjk71fv0ohngkrm40mf5ef2vb.apps.googleusercontent.com
#                      client-secret: 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
#                      scope:
#                          - email
#                          - profile
                  kakao:
                      client-id: e0511a8daec0ca7ab6300f28127d674e
                      client-secret: JbTBHXqb6vgTurrKRW9ii5glcXpvq7cI
                      client-authentication-method: client_secret_post
                      redirect-uri: http://localhost:8080/login/oauth2/code/kakao
                      authorization-grant-type: authorization_code
                      scope:
                          - profile_nickname
                          - account_email
                          - gender
                          - age_range
                          - birthday
              provider:
                  kakao:
                      authorization-uri: https://kauth.kakao.com/oauth/authorize
                      token-uri: https://kauth.kakao.com/oauth/token
                      user-info-uri: https://kapi.kakao.com/v2/user/me
                      user-name-attribute: id
                
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:com/cookccook/app/**/dao/mapper/*.xml
    
# 파일 업로드 커스텀 설정
app:
    multipart: #파일 업로드 정책 관련 설정
        # 업로드한 파일이 저장될 위치
        base-dir: C:/uploadFiles
        obfuscation: #파일명 난독화 관련 설정
            # 난독화 사용 여부
            enable: true
            hide-ext: #파일명에서 확장자를 숨길 것인지에 대한 설정
            
            
---
spring:
    config:
        activate:
            on-profile: prod 
    security:
        oauth2:
          resourceserver:
              jwt:
                  issuer-uri: krait4g@gmail.com
                  secret-key: spring-security-secret-key-random-token-key
          client:
              registration:
                  google:
                      client-id: 359584162819-bra9rhhhjk71fv0ohngkrm40mf5ef2vb.apps.googleusercontent.com
                      client-secret: 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
                      scope:
                          - email
                          - profile
                  kakao:
                      client-id: cf61dcff7022b464cbdb591245f5650d
                      client-secret: Udr1gmzeDN76IMvFWJlKK3fwuuF15dpP
                      client-authentication-method: client_secret_post
                      redirect-uri: http://localhost:8080/login/oauth2/code/kakao
                      # 카카오 젠킨스 설정 아직 미완성
                      authorization-grant-type: authorization_code
                      scope:
                          - profile_nickname
                          - account_email
                          - gender
                          - age_range
                          - birthday
              provider:
                  kakao:
                      authorization-uri: https://kauth.kakao.com/oauth/authorize
                      token-uri: https://kauth.kakao.com/oauth/token
                      user-info-uri: https://kapi.kakao.com/v2/user/me
                      user-name-attribute: id
  
